_target_: src.models.evi.EviLitModel

model:
  _target_: src.models.evi.Evi
  embedding_layer:
    _target_: src.models.common.AlldataEmbeddingLayer
    batch_type: ${data.batch_type}
    embedding_size: 5
  task_num: 3
  expert_num: 8
  expert_dims: [256]
  expert_dropout: [0.3]
  tower_dims: [128, 64, 32]
  tower_dropout: [0, 0, 0]


loss:
  _target_: src.models.evi.CvrAllSpaceMultiTaskLoss
  ctr_loss_proportion: 0.2
  cvr_loss_proportion: 0.5
  ctcvr_loss_proportion: 0.2
  unclick_space_loss_proportion: 1.0

lr: 0.001

weight_decay: 1.0e-6

batch_type: ${data.batch_type}

mi_ratio: 0.8
var_ratio: 5.0
info_layer_num: 2.0
